open_collective: twintaillauncher
ko_fi: twintailteam
liberapay: TwintailTeam
#buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: u/gh/tukandev
custom: "https://paypal.me/tukandevofficial"