name: Publish to WinGet
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: TwintailTeam.TTL
          max-versions-to-keep: 5
          installers-regex: '\.exe$' # Only .exe files
          token: ${{ secrets.WINGET_TOKEN }}
